{"name": "Validate response when invalid country code is passed -- @1.2 ", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/usr/local/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/stepimpl.py\", line 35, in step_impl\n    assert context.response.status_code == statuscode\n"}, "steps": [{"name": "When Request is sent to GET Covid-19 data with invalid \"@432\"", "status": "passed", "start": 1645086595768, "stop": 1645086596583}, {"name": "Then response is received with HTTP status code 400", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/usr/local/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/stepimpl.py\", line 35, in step_impl\n    assert context.response.status_code == statuscode\n"}, "start": 1645086596583, "stop": 1645086597094}, {"name": "And response should contain an error message as \"Invalid country code\"", "status": "skipped", "start": 1645086597095, "stop": 1645086597095}], "parameters": [{"name": "country_code", "value": "@432"}], "start": 1645086595767, "stop": 1645086597095, "uuid": "a29ad5e6-0fbf-44de-8561-0fa605384843", "historyId": "3a6d19f942691b133480cc723e77f354", "fullName": "Validation of GET Covid-19 data using Country Code endpoint: Validate response when invalid country code is passed", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Validation of GET Covid-19 data using Country Code endpoint"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}